# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7929d25b8c115c4f086be3c658a7a327"
application_url = "https://dista-aw-app-miduty-ea21.onrender.com"
embedded = true
name = "Dista AW App - Miduty"
handle = "dista-aw-app-miduty"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_write_customers,read_customers,read_orders,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://dista-aw-app-miduty-ea21.onrender.com/auth/callback",
  "https://dista-aw-app-miduty-ea21.onrender.com/auth/shopify/callback",
  "https://dista-aw-app-miduty-ea21.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://dista-aw-app-miduty-ea21.onrender.com"
subpath = "apw"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "distaxstaging.myshopify.com"
automatically_update_urls_on_dev = true
